cp -r ./public/tinymce/plugins/mark ./node_modules/tinymce/plugins
cp -r ./public/tinymce/plugins/newblock ./node_modules/tinymce/plugins
cp -r ./public/tinymce/plugins/pdfmedia ./node_modules/tinymce/plugins
cp -r ./public/tinymce/plugins/visualthymeleaf ./node_modules/tinymce/plugins
cp -r ./public/tinymce/plugins/lineheight ./node_modules/tinymce/plugins
cp -r ./public/tinymce/plugins/indent2em ./node_modules/tinymce/plugins
cp -r ./public/tinymce/plugins/pdfcon ./node_modules/tinymce/plugins
cp -r ./public/tinymce/plugins/hr ./node_modules/tinymce/plugins
cp -r ./public/tinymce/plugins/pagebreak ./node_modules/tinymce/plugins
cp -r ./public/tinymce/plugins/absdiv ./node_modules/tinymce/plugins
cp -r ./public/tinymce/icons ./node_modules/tinymce/
